# Generated by Django 3.1.1 on 2020-09-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_email_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='content_plain',
            field=models.TextField(blank=True),
        ),
    ]
